In [1]:
import pandas as pd
import numpy as np

In [3]:
# Series() is used for 1-d dataset
# Series is represented as indexes and values
pd.Series([10,20,30,40,50,60,70])

0    10
1    20
2    30
3    40
4    50
5    60
6    70
dtype: int64

In [7]:
# Collection of Series
data_series = {'Column1':pd.Series([10,20,30,40,50,60,70],index = ['a','b','c','d','e','f','g']),
 'Column2':pd.Series([100,200,300,400,500,600,700],index = ['a','b','c','d','e','f','g'])}

In [8]:
print(data_series)

{'Column1': a    10
b    20
c    30
d    40
e    50
f    60
g    70
dtype: int64, 'Column2': a    100
b    200
c    300
d    400
e    500
f    600
g    700
dtype: int64}

In [6]:
# Display dataframe
pd.DataFrame(data_series)

   Column1  Column2
0       10      100
1       20      200
2       30      300
3       40      400
4       50      500
5       60      600
6       70      700

In [9]:
# Create a DataFrame using dataset
autoprice_DF = pd.read_csv('Automobile_price_data__Raw_.csv')
autoprice_DF.head()

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450

In [10]:
display(autoprice_DF)

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845
201,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045
202,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485
203,-1,95,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.40,23.0,106,4800,26,27,22470
204,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625

In [11]:
# isnull() -> return missing value as True and Flase for not null
autoprice_DF.isnull()

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
201,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
202,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
203,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
204,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [13]:
# notnull -> returns missing value as False and True for not null
autoprice_DF.notnull()

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
1,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
2,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
3,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
4,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
201,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
202,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
203,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
204,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True

In [14]:
autoprice_DF.isnull().sum()

symboling            0
normalized-losses    0
make                 0
fuel-type            0
aspiration           0
num-of-doors         0
body-style           0
drive-wheels         0
engine-location      0
wheel-base           0
length               0
width                0
height               0
curb-weight          0
engine-type          0
num-of-cylinders     0
engine-size          0
fuel-system          0
bore                 0
stroke               0
compression-ratio    0
horsepower           0
peak-rpm             0
city-mpg             0
highway-mpg          0
price                0
dtype: int64

In [15]:
# sum of missing rows present in each column
autoprice_DF.isna().sum()

symboling            0
normalized-losses    0
make                 0
fuel-type            0
aspiration           0
num-of-doors         0
body-style           0
drive-wheels         0
engine-location      0
wheel-base           0
length               0
width                0
height               0
curb-weight          0
engine-type          0
num-of-cylinders     0
engine-size          0
fuel-system          0
bore                 0
stroke               0
compression-ratio    0
horsepower           0
peak-rpm             0
city-mpg             0
highway-mpg          0
price                0
dtype: int64

In [16]:
autoprice_DF.describe()

,symboling,wheel-base,length,width,height,curb-weight,engine-size,compression-ratio,city-mpg,highway-mpg
count,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000
mean,0.834146,98.756585,174.049268,65.907805,53.724878,2555.565854,126.907317,10.142537,25.219512,30.751220
std,1.245307,6.021776,12.337289,2.145204,2.443522,520.680204,41.642693,3.972040,6.542142,6.886443
min,-2.000000,86.600000,141.100000,60.300000,47.800000,1488.000000,61.000000,7.000000,13.000000,16.000000
25%,0.000000,94.500000,166.300000,64.100000,52.000000,2145.000000,97.000000,8.600000,19.000000,25.000000
50%,1.000000,97.000000,173.200000,65.500000,54.100000,2414.000000,120.000000,9.000000,24.000000,30.000000
75%,2.000000,102.400000,183.100000,66.900000,55.500000,2935.000000,141.000000,9.400000,30.000000,34.000000
max,3.000000,120.900000,208.100000,72.300000,59.800000,4066.000000,326.000000,23.000000,49.000000,54.000000

In [19]:
# replace '?' by np.nan
autoprice_DF.replace('?',np.nan,inplace = True)

In [20]:
# sum of missing rows present in each column
autoprice_DF.isna().sum()

symboling             0
normalized-losses    41
make                  0
fuel-type             0
aspiration            0
num-of-doors          2
body-style            0
drive-wheels          0
engine-location       0
wheel-base            0
length                0
width                 0
height                0
curb-weight           0
engine-type           0
num-of-cylinders      0
engine-size           0
fuel-system           0
bore                  4
stroke                4
compression-ratio     0
horsepower            2
peak-rpm              2
city-mpg              0
highway-mpg           0
price                 4
dtype: int64

In [21]:
#select 'price' column
autoprice_DF['price']

0      13495
1      16500
2      16500
3      13950
4      17450
       ...
200    16845
201    19045
202    21485
203    22470
204    22625
Name: price, Length: 205, dtype: object

In [26]:
autoprice_DF[autoprice_DF['price'].isnull() == True]

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
9,0,NaN,audi,gas,turbo,two,hatchback,4wd,front,99.5,...,131,mpfi,3.13,3.40,7.0,160,5500,16,22,NaN
44,1,NaN,isuzu,gas,std,two,sedan,fwd,front,94.5,...,90,2bbl,3.03,3.11,9.6,70,5400,38,43,NaN
45,0,NaN,isuzu,gas,std,four,sedan,fwd,front,94.5,...,90,2bbl,3.03,3.11,9.6,70,5400,38,43,NaN
129,1,NaN,porsche,gas,std,two,hatchback,rwd,front,98.4,...,203,mpfi,3.94,3.11,10.0,288,5750,17,28,NaN

In [27]:
autoprice_DF.head(10)

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,NaN,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450
5,2,NaN,audi,gas,std,two,sedan,fwd,front,99.8,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,15250
6,1,158,audi,gas,std,four,sedan,fwd,front,105.8,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,17710
7,1,NaN,audi,gas,std,four,wagon,fwd,front,105.8,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,18920
8,1,158,audi,gas,turbo,four,sedan,fwd,front,105.8,...,131,mpfi,3.13,3.40,8.3,140,5500,17,20,23875
9,0,NaN,audi,gas,turbo,two,hatchback,4wd,front,99.5,...,131,mpfi,3.13,3.40,7.0,160,5500,16,22,NaN

In [28]:
autoprice_DF.loc[0:11,]

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,NaN,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450
5,2,NaN,audi,gas,std,two,sedan,fwd,front,99.8,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,15250
6,1,158,audi,gas,std,four,sedan,fwd,front,105.8,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,17710
7,1,NaN,audi,gas,std,four,wagon,fwd,front,105.8,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,18920
8,1,158,audi,gas,turbo,four,sedan,fwd,front,105.8,...,131,mpfi,3.13,3.40,8.3,140,5500,17,20,23875
9,0,NaN,audi,gas,turbo,two,hatchback,4wd,front,99.5,...,131,mpfi,3.13,3.40,7.0,160,5500,16,22,NaN
10,2,192,bmw,gas,std,two,sedan,rwd,front,101.2,...,108,mpfi,3.50,2.80,8.8,101,5800,23,29,16430
11,0,192,bmw,gas,std,four,sedan,rwd,front,101.2,...,108,mpfi,3.50,2.80,8.8,101,5800,23,29,16925

In [31]:
autoprice_DF.loc[:,['make','fuel-type']]

            make fuel-type
0    alfa-romero       gas
1    alfa-romero       gas
2    alfa-romero       gas
3           audi       gas
4           audi       gas
..           ...       ...
200        volvo       gas
201        volvo       gas
202        volvo       gas
203        volvo    diesel
204        volvo       gas

[205 rows x 2 columns]

In [33]:
# start index = 'make',  stop_index = 'height'
autoprice_DF.loc[:,'make':'height']

,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,length,width,height
0,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,64.1,48.8
1,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,64.1,48.8
2,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,171.2,65.5,52.4
3,audi,gas,std,four,sedan,fwd,front,99.8,176.6,66.2,54.3
4,audi,gas,std,four,sedan,4wd,front,99.4,176.6,66.4,54.3
...,...,...,...,...,...,...,...,...,...,...,...
200,volvo,gas,std,four,sedan,rwd,front,109.1,188.8,68.9,55.5
201,volvo,gas,turbo,four,sedan,rwd,front,109.1,188.8,68.8,55.5
202,volvo,gas,std,four,sedan,rwd,front,109.1,188.8,68.9,55.5
203,volvo,diesel,turbo,four,sedan,rwd,front,109.1,188.8,68.9,55.5
204,volvo,gas,turbo,four,sedan,rwd,front,109.1,188.8,68.9,55.5

In [35]:
# It slices data by row index and column index value
autoprice_DF.iloc[:,2:13]

,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,length,width,height
0,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,64.1,48.8
1,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,64.1,48.8
2,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,171.2,65.5,52.4
3,audi,gas,std,four,sedan,fwd,front,99.8,176.6,66.2,54.3
4,audi,gas,std,four,sedan,4wd,front,99.4,176.6,66.4,54.3
...,...,...,...,...,...,...,...,...,...,...,...
200,volvo,gas,std,four,sedan,rwd,front,109.1,188.8,68.9,55.5
201,volvo,gas,turbo,four,sedan,rwd,front,109.1,188.8,68.8,55.5
202,volvo,gas,std,four,sedan,rwd,front,109.1,188.8,68.9,55.5
203,volvo,diesel,turbo,four,sedan,rwd,front,109.1,188.8,68.9,55.5
204,volvo,gas,turbo,four,sedan,rwd,front,109.1,188.8,68.9,55.5

### Sort Values
    * sort_values()

In [40]:
autoprice_DF.sort_values(by = ['make'],ascending=False).head(20)

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
204,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625
199,-1,74,volvo,gas,turbo,four,wagon,rwd,front,104.3,...,130,mpfi,3.62,3.15,7.5,162,5100,17,22,18950
194,-2,103,volvo,gas,std,four,sedan,rwd,front,104.3,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,12940
195,-1,74,volvo,gas,std,four,wagon,rwd,front,104.3,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,13415
196,-2,103,volvo,gas,std,four,sedan,rwd,front,104.3,...,141,mpfi,3.78,3.15,9.5,114,5400,24,28,15985
198,-2,103,volvo,gas,turbo,four,sedan,rwd,front,104.3,...,130,mpfi,3.62,3.15,7.5,162,5100,17,22,18420
197,-1,74,volvo,gas,std,four,wagon,rwd,front,104.3,...,141,mpfi,3.78,3.15,9.5,114,5400,24,28,16515
200,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845
201,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045
202,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485
203,-1,95,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.40,23.0,106,4800,26,27,22470
188,2,94,volkswagen,gas,std,four,sedan,fwd,front,97.3,...,109,mpfi,3.19,3.40,10.0,100,5500,26,32,9995
182,2,122,volkswagen,diesel,std,two,sedan,fwd,front,97.3,...,97,idi,3.01,3.40,23.0,52,4800,37,46,7775
183,2,122,volkswagen,gas,std,two,sedan,fwd,front,97.3,...,109,mpfi,3.19,3.40,9.0,85,5250,27,34,7975
184,2,94,volkswagen,diesel,std,four,sedan,fwd,front,97.3,...,97,idi,3.01,3.40,23.0,52,4800,37,46,7995
185,2,94,volkswagen,gas,std,four,sedan,fwd,front,97.3,...,109,mpfi,3.19,3.40,9.0,85,5250,27,34,8195
187,2,94,volkswagen,diesel,turbo,four,sedan,fwd,front,97.3,...,97,idi,3.01,3.40,23.0,68,4500,37,42,9495
186,2,94,volkswagen,gas,std,four,sedan,fwd,front,97.3,...,109,mpfi,3.19,3.40,9.0,85,5250,27,34,8495
189,3,NaN,volkswagen,gas,std,two,convertible,fwd,front,94.5,...,109,mpfi,3.19,3.40,8.5,90,5500,24,29,11595
190,3,256,volkswagen,gas,std,two,hatchback,fwd,front,94.5,...,109,mpfi,3.19,3.40,8.5,90,5500,24,29,9980

In [42]:
autoprice_DF['horsepower'] = autoprice_DF['horsepower'].astype('float16')

In [44]:
autoprice_DF['horsepower'].sort_values()

18      48.0
182     52.0
184     52.0
90      55.0
158     56.0
       ...
126    207.0
49     262.0
129    288.0
130      NaN
131      NaN
Name: horsepower, Length: 205, dtype: float16

In [45]:
autoprice_DF.sort_values(by = 'horsepower',ascending=False).head(15)

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
129,1,NaN,porsche,gas,std,two,hatchback,rwd,front,98.4,...,203,mpfi,3.94,3.11,10.0,288.0,5750,17,28,NaN
49,0,NaN,jaguar,gas,std,two,sedan,rwd,front,102.0,...,326,mpfi,3.54,2.76,11.5,262.0,5000,13,17,36000
128,3,NaN,porsche,gas,std,two,convertible,rwd,rear,89.5,...,194,mpfi,3.74,2.90,9.5,207.0,5900,17,25,37028
127,3,NaN,porsche,gas,std,two,hardtop,rwd,rear,89.5,...,194,mpfi,3.74,2.90,9.5,207.0,5900,17,25,34028
126,3,NaN,porsche,gas,std,two,hardtop,rwd,rear,89.5,...,194,mpfi,3.74,2.90,9.5,207.0,5900,17,25,32528
105,3,194,nissan,gas,turbo,two,hatchback,rwd,front,91.3,...,181,mpfi,3.43,3.27,7.8,200.0,5200,17,23,19699
73,0,NaN,mercedes-benz,gas,std,four,sedan,rwd,front,120.9,...,308,mpfi,3.80,3.35,8.0,184.0,4500,14,16,40960
74,1,NaN,mercedes-benz,gas,std,two,hardtop,rwd,front,112.0,...,304,mpfi,3.80,3.35,8.0,184.0,4500,14,16,45400
17,0,NaN,bmw,gas,std,four,sedan,rwd,front,110.0,...,209,mpfi,3.62,3.39,8.0,182.0,5400,15,20,36880
16,0,NaN,bmw,gas,std,two,sedan,rwd,front,103.5,...,209,mpfi,3.62,3.39,8.0,182.0,5400,16,22,41315
15,0,NaN,bmw,gas,std,four,sedan,rwd,front,103.5,...,209,mpfi,3.62,3.39,8.0,182.0,5400,16,22,30760
48,0,NaN,jaguar,gas,std,four,sedan,rwd,front,113.0,...,258,mpfi,3.63,4.17,8.1,176.0,4750,15,19,35550
47,0,145,jaguar,gas,std,four,sedan,rwd,front,113.0,...,258,mpfi,3.63,4.17,8.1,176.0,4750,15,19,32250
75,1,NaN,mercury,gas,turbo,two,hatchback,rwd,front,102.7,...,140,mpfi,3.78,3.12,8.0,175.0,5000,19,24,16503
198,-2,103,volvo,gas,turbo,four,sedan,rwd,front,104.3,...,130,mpfi,3.62,3.15,7.5,162.0,5100,17,22,18420

In [46]:
autoprice_DF.sort_values(by = ['make','horsepower'],ascending=[False,True]).head(15)

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
203,-1,95,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.40,23.0,106.0,4800,26,27,22470
194,-2,103,volvo,gas,std,four,sedan,rwd,front,104.3,...,141,mpfi,3.78,3.15,9.5,114.0,5400,23,28,12940
195,-1,74,volvo,gas,std,four,wagon,rwd,front,104.3,...,141,mpfi,3.78,3.15,9.5,114.0,5400,23,28,13415
196,-2,103,volvo,gas,std,four,sedan,rwd,front,104.3,...,141,mpfi,3.78,3.15,9.5,114.0,5400,24,28,15985
197,-1,74,volvo,gas,std,four,wagon,rwd,front,104.3,...,141,mpfi,3.78,3.15,9.5,114.0,5400,24,28,16515
200,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114.0,5400,23,28,16845
204,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114.0,5400,19,25,22625
202,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134.0,5500,18,23,21485
201,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160.0,5300,19,25,19045
198,-2,103,volvo,gas,turbo,four,sedan,rwd,front,104.3,...,130,mpfi,3.62,3.15,7.5,162.0,5100,17,22,18420
199,-1,74,volvo,gas,turbo,four,wagon,rwd,front,104.3,...,130,mpfi,3.62,3.15,7.5,162.0,5100,17,22,18950
182,2,122,volkswagen,diesel,std,two,sedan,fwd,front,97.3,...,97,idi,3.01,3.40,23.0,52.0,4800,37,46,7775
184,2,94,volkswagen,diesel,std,four,sedan,fwd,front,97.3,...,97,idi,3.01,3.40,23.0,52.0,4800,37,46,7995
187,2,94,volkswagen,diesel,turbo,four,sedan,fwd,front,97.3,...,97,idi,3.01,3.40,23.0,68.0,4500,37,42,9495
192,0,NaN,volkswagen,diesel,turbo,four,sedan,fwd,front,100.4,...,97,idi,3.01,3.40,23.0,68.0,4500,33,38,13845

In [48]:
# show unique vales from a column
autoprice_DF['make'].unique()

array(['alfa-romero', 'audi', 'bmw', 'chevrolet', 'dodge', 'honda',
       'isuzu', 'jaguar', 'mazda', 'mercedes-benz', 'mercury',
       'mitsubishi', 'nissan', 'peugot', 'plymouth', 'porsche', 'renault',
       'saab', 'subaru', 'toyota', 'volkswagen', 'volvo'], dtype=object)

In [52]:
# show frequency of elements
autoprice_DF['make'].value_counts().sort_valueslues()

mercury           1
renault           2
alfa-romero       3
chevrolet         3
jaguar            3
isuzu             4
porsche           5
saab              6
plymouth          7
audi              7
bmw               8
mercedes-benz     8
dodge             9
volvo            11
peugot           11
subaru           12
volkswagen       12
honda            13
mitsubishi       13
mazda            17
nissan           18
toyota           32
Name: make, dtype: int64

In [51]:
type(autoprice_DF['make'].value_counts())

pandas.core.series.Series

### Drop function
    * Dropping rows, dropping columns

In [54]:
# dropping is default by row
autoprice_DF.drop([0,1,2,3,4,5,6,7,8])

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
9,0,NaN,audi,gas,turbo,two,hatchback,4wd,front,99.5,...,131,mpfi,3.13,3.40,7.0,160.0,5500,16,22,NaN
10,2,192,bmw,gas,std,two,sedan,rwd,front,101.2,...,108,mpfi,3.50,2.80,8.8,101.0,5800,23,29,16430
11,0,192,bmw,gas,std,four,sedan,rwd,front,101.2,...,108,mpfi,3.50,2.80,8.8,101.0,5800,23,29,16925
12,0,188,bmw,gas,std,two,sedan,rwd,front,101.2,...,164,mpfi,3.31,3.19,9.0,121.0,4250,21,28,20970
13,0,188,bmw,gas,std,four,sedan,rwd,front,101.2,...,164,mpfi,3.31,3.19,9.0,121.0,4250,21,28,21105
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114.0,5400,23,28,16845
201,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160.0,5300,19,25,19045
202,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134.0,5500,18,23,21485
203,-1,95,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.40,23.0,106.0,4800,26,27,22470
204,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114.0,5400,19,25,22625

In [57]:
# drop columns
autoprice_DF.drop(['symboling','normalized-losses'],axis = 1,inplace = True)
autoprice_DF.head()

,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,length,width,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,64.1,...,130,mpfi,3.47,2.68,9.0,111.0,5000,21,27,13495
1,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,64.1,...,130,mpfi,3.47,2.68,9.0,111.0,5000,21,27,16500
2,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,171.2,65.5,...,152,mpfi,2.68,3.47,9.0,154.0,5000,19,26,16500
3,audi,gas,std,four,sedan,fwd,front,99.8,176.6,66.2,...,109,mpfi,3.19,3.40,10.0,102.0,5500,24,30,13950
4,audi,gas,std,four,sedan,4wd,front,99.4,176.6,66.4,...,136,mpfi,3.19,3.40,8.0,115.0,5500,18,22,17450

In [ ]:
autoprice_DF.drop(['aspiration':'drive-wheels'],axis = 1,inplace = True)

In [58]:
autoprice_DF.drop([0,1,2,3,4,5,6,7,8],axis = 0).reset_index().drop('index',axis = 1)

,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,length,width,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,audi,gas,turbo,two,hatchback,4wd,front,99.5,178.2,67.9,...,131,mpfi,3.13,3.40,7.0,160.0,5500,16,22,NaN
1,bmw,gas,std,two,sedan,rwd,front,101.2,176.8,64.8,...,108,mpfi,3.50,2.80,8.8,101.0,5800,23,29,16430
2,bmw,gas,std,four,sedan,rwd,front,101.2,176.8,64.8,...,108,mpfi,3.50,2.80,8.8,101.0,5800,23,29,16925
3,bmw,gas,std,two,sedan,rwd,front,101.2,176.8,64.8,...,164,mpfi,3.31,3.19,9.0,121.0,4250,21,28,20970
4,bmw,gas,std,four,sedan,rwd,front,101.2,176.8,64.8,...,164,mpfi,3.31,3.19,9.0,121.0,4250,21,28,21105
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
191,volvo,gas,std,four,sedan,rwd,front,109.1,188.8,68.9,...,141,mpfi,3.78,3.15,9.5,114.0,5400,23,28,16845
192,volvo,gas,turbo,four,sedan,rwd,front,109.1,188.8,68.8,...,141,mpfi,3.78,3.15,8.7,160.0,5300,19,25,19045
193,volvo,gas,std,four,sedan,rwd,front,109.1,188.8,68.9,...,173,mpfi,3.58,2.87,8.8,134.0,5500,18,23,21485
194,volvo,diesel,turbo,four,sedan,rwd,front,109.1,188.8,68.9,...,145,idi,3.01,3.40,23.0,106.0,4800,26,27,22470
195,volvo,gas,turbo,four,sedan,rwd,front,109.1,188.8,68.9,...,141,mpfi,3.78,3.15,9.5,114.0,5400,19,25,22625

In [59]:
autoprice_DF[autoprice_DF['make']=='audi']

,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,length,width,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
3,audi,gas,std,four,sedan,fwd,front,99.8,176.6,66.2,...,109,mpfi,3.19,3.40,10.0,102.0,5500,24,30,13950
4,audi,gas,std,four,sedan,4wd,front,99.4,176.6,66.4,...,136,mpfi,3.19,3.40,8.0,115.0,5500,18,22,17450
5,audi,gas,std,two,sedan,fwd,front,99.8,177.3,66.3,...,136,mpfi,3.19,3.40,8.5,110.0,5500,19,25,15250
6,audi,gas,std,four,sedan,fwd,front,105.8,192.7,71.4,...,136,mpfi,3.19,3.40,8.5,110.0,5500,19,25,17710
7,audi,gas,std,four,wagon,fwd,front,105.8,192.7,71.4,...,136,mpfi,3.19,3.40,8.5,110.0,5500,19,25,18920
8,audi,gas,turbo,four,sedan,fwd,front,105.8,192.7,71.4,...,131,mpfi,3.13,3.40,8.3,140.0,5500,17,20,23875
9,audi,gas,turbo,two,hatchback,4wd,front,99.5,178.2,67.9,...,131,mpfi,3.13,3.40,7.0,160.0,5500,16,22,NaN

In [ ]:
autoprice_DF.filter()

In [70]:
autoprice_DF.filter(items ='make',like =='audi')#== 'audi'

SyntaxError: positional argument follows keyword argument (1044811948.py, line 1)

In [72]:
autoprice_DF[(autoprice_DF['make']=='audi') & (autoprice_DF['horsepower']>110)]

,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,length,width,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
4,audi,gas,std,four,sedan,4wd,front,99.4,176.6,66.4,...,136,mpfi,3.19,3.40,8.0,115.0,5500,18,22,17450
8,audi,gas,turbo,four,sedan,fwd,front,105.8,192.7,71.4,...,131,mpfi,3.13,3.40,8.3,140.0,5500,17,20,23875
9,audi,gas,turbo,two,hatchback,4wd,front,99.5,178.2,67.9,...,131,mpfi,3.13,3.40,7.0,160.0,5500,16,22,NaN

In [73]:
# sample
autoprice_DF.sample(10)

,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,length,width,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
24,dodge,gas,std,four,hatchback,fwd,front,93.7,157.3,63.8,...,90,2bbl,2.97,3.23,9.4,68.0,5500,31,38,6229
107,peugot,gas,std,four,sedan,rwd,front,107.9,186.7,68.4,...,120,mpfi,3.46,3.19,8.4,97.0,5000,19,24,11900
27,dodge,gas,turbo,NaN,sedan,fwd,front,93.7,157.3,63.8,...,98,mpfi,3.03,3.39,7.6,102.0,5500,24,30,8558
91,nissan,gas,std,two,sedan,fwd,front,94.5,165.3,63.8,...,97,2bbl,3.15,3.29,9.4,69.0,5200,31,37,6649
20,chevrolet,gas,std,four,sedan,fwd,front,94.5,158.8,63.6,...,90,2bbl,3.03,3.11,9.6,70.0,5400,38,43,6575
79,mitsubishi,gas,turbo,two,hatchback,fwd,front,93.0,157.3,63.8,...,98,spdi,3.03,3.39,7.6,102.0,5500,24,30,7689
101,nissan,gas,std,four,sedan,fwd,front,100.4,181.7,66.5,...,181,mpfi,3.43,3.27,9.0,152.0,5200,17,22,13499
154,toyota,gas,std,four,wagon,4wd,front,95.7,169.7,63.6,...,92,2bbl,3.05,3.03,9.0,62.0,4800,27,32,7898
116,peugot,diesel,turbo,four,sedan,rwd,front,107.9,186.7,68.4,...,152,idi,3.70,3.52,21.0,95.0,4150,28,33,17950
120,plymouth,gas,std,four,hatchback,fwd,front,93.7,157.3,63.8,...,90,2bbl,2.97,3.23,9.4,68.0,5500,31,38,6229

In [74]:
autoprice_DF.sample(frac = 0.1)

,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,length,width,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
99,nissan,gas,std,four,hatchback,fwd,front,97.2,173.4,65.2,...,120,2bbl,3.33,3.47,8.5,97.0,5200,27,34,8949
76,mitsubishi,gas,std,two,hatchback,fwd,front,93.7,157.3,64.4,...,92,2bbl,2.97,3.23,9.4,68.0,5500,37,41,5389
166,toyota,gas,std,two,hatchback,rwd,front,94.5,168.7,64.0,...,98,mpfi,3.24,3.08,9.4,112.0,6600,26,29,9538
176,toyota,gas,std,four,sedan,fwd,front,102.4,175.6,66.5,...,122,mpfi,3.31,3.54,8.7,92.0,4200,27,32,10898
36,honda,gas,std,four,wagon,fwd,front,96.5,157.1,63.9,...,92,1bbl,2.92,3.41,9.2,76.0,6000,30,34,7295
119,plymouth,gas,turbo,two,hatchback,fwd,front,93.7,157.3,63.8,...,98,spdi,3.03,3.39,7.6,102.0,5500,24,30,7957
58,mazda,gas,std,two,hatchback,rwd,front,95.3,169.0,65.7,...,80,mpfi,NaN,NaN,9.4,135.0,6000,16,23,15645
12,bmw,gas,std,two,sedan,rwd,front,101.2,176.8,64.8,...,164,mpfi,3.31,3.19,9.0,121.0,4250,21,28,20970
111,peugot,gas,std,four,sedan,rwd,front,107.9,186.7,68.4,...,120,mpfi,3.46,2.19,8.4,95.0,5000,19,24,15580
66,mazda,diesel,std,four,sedan,rwd,front,104.9,175.0,66.1,...,134,idi,3.43,3.64,22.0,72.0,4200,31,39,18344
40,honda,gas,std,four,sedan,fwd,front,96.5,175.4,62.5,...,110,1bbl,3.15,3.58,9.0,86.0,5800,27,33,10295
97,nissan,gas,std,four,wagon,fwd,front,94.5,170.2,63.8,...,97,2bbl,3.15,3.29,9.4,69.0,5200,31,37,7999
186,volkswagen,gas,std,four,sedan,fwd,front,97.3,171.7,65.5,...,109,mpfi,3.19,3.40,9.0,85.0,5250,27,34,8495
68,mercedes-benz,diesel,turbo,four,wagon,rwd,front,110.0,190.9,70.3,...,183,idi,3.58,3.64,21.5,123.0,4350,22,25,28248
63,mazda,diesel,std,NaN,sedan,fwd,front,98.8,177.8,66.5,...,122,idi,3.39,3.39,22.7,64.0,4650,36,42,10795
49,jaguar,gas,std,two,sedan,rwd,front,102.0,191.7,70.6,...,326,mpfi,3.54,2.76,11.5,262.0,5000,13,17,36000
59,mazda,gas,std,two,hatchback,fwd,front,98.8,177.8,66.5,...,122,2bbl,3.39,3.39,8.6,84.0,4800,26,32,8845
26,dodge,gas,std,four,sedan,fwd,front,93.7,157.3,63.8,...,90,2bbl,2.97,3.23,9.4,68.0,5500,31,38,7609
113,peugot,gas,std,four,wagon,rwd,front,114.2,198.9,68.4,...,120,mpfi,3.46,2.19,8.4,95.0,5000,19,24,16695
159,toyota,diesel,std,four,hatchback,fwd,front,95.7,166.3,64.4,...,110,idi,3.27,3.35,22.5,56.0,4500,38,47,7788

In [75]:
autoprice_DF.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
200    False
201    False
202    False
203    False
204    False
Length: 205, dtype: bool

In [89]:
auto_df = autoprice_DF[['make']]

In [90]:
auto_df['dup_make'] = autoprice_DF[['make']]

C:\Users\neroy\AppData\Local\Temp\ipykernel_16976\2753720916.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  auto_df['dup_make'] = autoprice_DF[['make']]

In [91]:
auto_df['length'] = autoprice_DF[['length']]

C:\Users\neroy\AppData\Local\Temp\ipykernel_16976\738970939.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  auto_df['length'] = autoprice_DF[['length']]

In [92]:
auto_df

            make     dup_make  length
0    alfa-romero  alfa-romero   168.8
1    alfa-romero  alfa-romero   168.8
2    alfa-romero  alfa-romero   171.2
3           audi         audi   176.6
4           audi         audi   176.6
..           ...          ...     ...
200        volvo        volvo   188.8
201        volvo        volvo   188.8
202        volvo        volvo   188.8
203        volvo        volvo   188.8
204        volvo        volvo   188.8

[205 rows x 3 columns]

In [94]:
type(auto_df)

pandas.core.frame.DataFrame

In [98]:
auto_df[auto_df.duplicated()].index

Int64Index([  1,   4,   7,   8,  11,  12,  13,  15,  22,  23,
            ...
            195, 196, 197, 198, 199, 200, 201, 202, 203, 204],
           dtype='int64', length=121)

In [99]:
auto_df.duplicated()

0      False
1       True
2      False
3      False
4       True
       ...
200     True
201     True
202     True
203     True
204     True
Length: 205, dtype: bool

In [100]:
df = pd.DataFrame({
...     'brand': ['Yum Yum', 'Yum Yum', 'Indomie', 'Indomie', 'Indomie'],
...     'style': ['cup', 'cup', 'cup', 'pack', 'pack'],
...     'rating': [4, 4, 3.5, 15, 5]
... })

In [103]:
print(df)
df.duplicated()

     brand style  rating
0  Yum Yum   cup     4.0
1  Yum Yum   cup     4.0
2  Indomie   cup     3.5
3  Indomie  pack    15.0
4  Indomie  pack     5.0

0    False
1     True
2    False
3    False
4    False
dtype: bool

In [104]:
df[df.duplicated()]

     brand style  rating
1  Yum Yum   cup     4.0

In [106]:
df[df.duplicated()].index

Int64Index([1], dtype='int64')

### Groupby()

In [111]:
autoprice_DF.groupby('make')[['city-mpg']].mean()

                city-mpg
make
alfa-romero    20.333333
audi           18.857143
bmw            19.375000
chevrolet      41.000000
dodge          28.000000
honda          30.384615
isuzu          31.000000
jaguar         14.333333
mazda          25.705882
mercedes-benz  18.500000
mercury        19.000000
mitsubishi     24.923077
nissan         27.000000
peugot         22.454545
plymouth       28.142857
porsche        17.400000
renault        23.000000
saab           20.333333
subaru         26.333333
toyota         27.500000
volkswagen     28.583333
volvo          21.181818

In [112]:
autoprice_DF.groupby('make').mean('city-mpg').sort_values(by = 'city-mpg',ascending = False)

,wheel-base,length,width,height,curb-weight,engine-size,compression-ratio,horsepower,city-mpg,highway-mpg
make,,,,,,,,,,
chevrolet,92.466667,151.933333,62.500000,52.400000,1757.000000,80.333333,9.566667,62.65625,41.000000,46.333333
isuzu,94.825000,163.775000,63.550000,52.225000,2213.500000,102.500000,9.225000,77.00000,31.000000,36.000000
honda,94.330769,160.769231,64.384615,53.238462,2096.769231,99.307692,9.215385,80.25000,30.384615,35.461538
volkswagen,97.608333,172.533333,65.616667,55.183333,2343.166667,107.250000,13.625000,81.06250,28.583333,34.916667
plymouth,95.385714,164.900000,64.271429,51.971429,2220.857143,106.285714,8.671429,86.68750,28.142857,34.142857
dodge,95.011111,160.988889,64.166667,51.644444,2151.333333,102.666667,8.634444,86.31250,28.000000,34.111111
toyota,98.103125,171.934375,65.090625,53.721875,2441.093750,118.812500,10.340625,92.75000,27.500000,32.906250
nissan,95.722222,170.988889,65.088889,53.633333,2400.388889,127.888889,9.794444,102.56250,27.000000,32.944444
subaru,96.175000,168.858333,64.950000,53.750000,2316.250000,107.083333,8.816667,86.25000,26.333333,30.750000
mazda,97.017647,170.805882,65.588235,53.358824,2297.823529,103.000000,10.488235,85.50000,25.705882,31.941176
mitsubishi,95.353846,168.030769,65.253846,50.692308,2381.923077,118.307692,8.061538,104.06250,24.923077,31.153846
renault,96.100000,179.150000,66.550000,52.850000,2519.500000,132.000000,8.700000,NaN,23.000000,31.000000
peugot,110.200000,191.136364,68.390909,57.181818,3221.000000,135.818182,14.000000,99.81250,22.454545,26.636364
volvo,106.481818,188.800000,67.963636,56.236364,3037.909091,142.272727,10.227273,128.00000,21.181818,25.818182
saab,99.100000,186.600000,66.500000,56.100000,2745.500000,121.000000,9.201667,126.68750,20.333333,27.333333
alfa-romero,90.566667,169.600000,64.566667,50.000000,2639.666667,137.333333,9.000000,125.31250,20.333333,26.666667
bmw,103.162500,184.500000,66.475000,54.825000,2929.375000,166.875000,8.575000,138.87500,19.375000,25.375000
mercury,102.700000,178.400000,68.000000,54.800000,2910.000000,140.000000,8.000000,175.00000,19.000000,24.000000
audi,102.271429,183.828571,68.714286,54.428571,2800.714286,130.714286,8.400000,121.00000,18.857143,24.142857
mercedes-benz,110.925000,195.262500,71.062500,55.725000,3696.250000,226.500000,14.825000,146.25000,18.500000,21.000000
porsche,92.280000,170.260000,67.120000,51.100000,2891.200000,187.200000,9.600000,210.37500,17.400000,26.000000
jaguar,109.333333,196.966667,69.933333,51.133333,4027.333333,280.666667,9.233333,204.62500,14.333333,18.333333

In [110]:
autoprice_DF.groupby('make')[['city-mpg']].mean().sort_values(by = 'city-mpg',ascending = False)

                city-mpg
make
chevrolet      41.000000
isuzu          31.000000
honda          30.384615
volkswagen     28.583333
plymouth       28.142857
dodge          28.000000
toyota         27.500000
nissan         27.000000
subaru         26.333333
mazda          25.705882
mitsubishi     24.923077
renault        23.000000
peugot         22.454545
volvo          21.181818
saab           20.333333
alfa-romero    20.333333
bmw            19.375000
mercury        19.000000
audi           18.857143
mercedes-benz  18.500000
porsche        17.400000
jaguar         14.333333